saltstack-formulas/packages-formula

- .kitchen.yml
- CHANGELOG.rst
- README.rst
- packages/map.jinja
- packages/osmap.yaml
As @aboe76 [suggested](https://github.com/saltstack-formulas/packages-formula/pull/5#issuecomment-368254418), added Fedora support in an `osmap.yaml` file.
> Add fedora support in an osmap

- .kitchen.yml
- README.rst
- packages/defaults.yaml
- packages/init.sls
- packages/osmap.yaml
- packages/snaps.sls
- pillar.example
This PR adds formula support for [snapd package manager](https://docs.snapcraft.io/core/snapd).  
Verified on Fedora:
```
$ sudo salt-call state.highstate --local
[ERROR   ] Command '['dnf', 'versionlock', 'list']' failed with return code: 1
[ERROR   ] output: No such command: versionlock. Please use /usr/bin/dnf --help
It could be a DNF plugin command, try: "dnf install 'dnf-command(versionlock)'"
[ERROR   ] Command '['dnf', 'versionlock', 'list']' failed with return code: 1
[ERROR   ] output: No such command: versionlock. Please use /usr/bin/dnf --help
It could be a DNF plugin command, try: "dnf install 'dnf-command(versionlock)'"
local:
----------
ID: pkg_req_pkgs
Function: pkg.installed
Result: True
Comment: The following packages were installed/updated: snapd
Started: 10:15:09.328165 …
```
> Add support for snapd package manager

- README.rst
- packages/osmap.yaml
- packages/snaps.sls
This PR is to ensure snapd state does not run on Centos.
```
ID: pkg_req_pkgs
Function: pkg.installed
Result: False
Comment: Error occurred installing package(s). Additional info follows:
errors:
- Running scope as unit run-16643.scope.
Loaded plugins: fastestmirror, versionlock
Loading mirror speeds from cached hostfile
* base: linux.cc.lehigh.edu
* epel: mirror.sfo12.us.leaseweb.net
* extras: linux.cc.lehigh.edu
* updates: mirror.net.cen.ct.gov
No package snapd available.
Error: Nothing to do
```
> no native snapd package on Centos

- packages/osfamilymap.yaml
I have not tested on FreeBSD, but this is correct stanza for `osfamilymap.yaml.`
> add FreeBSD to osfamilymap

- .kitchen.yml
- README.rst
- packages/archives.sls
- packages/defaults.yaml
- packages/init.sls
- pillar.example
Resolves #25 
Tested on Centos7 for archives of type `tar`  (tar.gz, tar.bz2).
Sample Pillars
```
packages:
archives:
wanted:
terminator:
dest: /usr/local/terminator
dl:
format: tar.gz
source: https://launchpad.net/terminator/gtk3/1.91/+download/terminator-1.91.tar.gz
hashurl: https://launchpad.net/terminator/gtk3/1.91/+download/terminator-1.91.tar.gz/+md5
phantomjs:
dest: /usr/local/phantomjs
user: root
mode: '0700'
dl:
format: tar.bz2
source: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
hashsum: 80e03cfeb22cc4dfe4e73b68ab81c9fdd7c78968cfd5358e6af33960464f15e3
unwanted:
- /usr/local/boring_archive_software
```
Sample output
```
local:
----------
ID: pkg_req_pkgs
Function: pkg.installed
Result: True
Comment: All specified packages are already …
```
> Support for 'archive file' format

- .kitchen.yml
- README.rst
- packages/archives.sls
- packages/defaults.yaml
- pillar.example
This PR  is improved implementation `packages.archives` state.  
1. Don't lose archive name => pull the filename from end of the URL so its proper filename.
```
{%- set archivename = archive.dl.source.split("/")[-1] %}
``` 
2. Allow support for downloading **raw** file format (i.e. `format: yaml`, `format: txt`, etc).  This is useful for downloading some kind of xml/json/yaml file, for docker compose for example.
3. Skip `archive.extracted` when **raw** file format (i.e. not a linux archive format) since you cannot archive extract a yaml file ;-)
4. Remove superfluous `packages-archive-wanted-install-{{ package }}.cmd.run`.
Verified on vagrant (three files: 2 = tar.gz and 1 = yaml).
```
Succeeded: 27 (changed=15)
Failed:     0
-------------
Total states run:     27
Total run time: …
```
> Improved packages.archive state

- packages/archives.sls
- packages/defaults.yaml
This PR fixes issue #38.  Tar is always bundled with MacOS so no homebrew package exists.
> tar is bundled with MacOS. Fix #38

- packages/archives.sls
Sometimes when using the `packages.archives` state I get a timeout. There are various potential causes - so a retry would be useful 
```
[ERROR   ] Failed to cache https://storage.googleapis.com/kubernetes-release/release/v1.11.0/bin/linux/amd64/kubectl: Error: HTTP 599: Timeout while connecting reading https://storage.googleapis.com/kubernetes-release/release/v1.11.0/bin/linux/amd64/kubectl
```
> Retry packages.archives download state

- packages/archives.sls
Its wasteful downloading fresh archive if the local cached already exists (with valid hashsum).
This PR will reduce average execution time for repeated runs of `archive` state.
> Avoid unnecessary archive downloads

- packages/osfamilymap.yaml
This PR is related to https://github.com/saltstack-formulas/docker-formula/issues/198
Here is state _before and after_ running salt-bootstrap on OpenSUSE 15.0
```
selenium-node:~/opensds-installer/salt # pip --version
pip 10.0.1 from /usr/lib/python3.6/site-packages/pip (python 3.6)
selenium-node:~/opensds-installer/salt # rpm -qa | grep pip
python3-pip-10.0.1-lp150.1.2.noarch
````
To avoid breaking python on latest Suse we should default to python3-pip.
> Python3 is default on Suse 15.0

- packages/pips.sls
This PR is workaround for broken pip.install/remove states with python3 (on Suse 15_0)
See: https://github.com/saltstack-formulas/docker-formula/issues/198
VERIFIED ON SUSE 15.0
```
ID: packages pips install tox
Function: cmd.run
Name: /usr/bin/pip install tox
Result: True
Comment: Command "/usr/bin/pip install tox" run
Started: 09:08:12.537061
Duration: 681.493 ms
Changes:
----------
pid:
5206
retcode:
0
stderr:
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
stdout:
Requirement already satisfied: tox in /usr/lib/python3.6/site-packages (3.7.0)
Requirement already satisfied: setuptools>=30.0.0 in /usr/lib/python3.6/site-packages (from tox) (38.4.1)
Requirement already satisfied: …
```
> pip states broken on python3 [suse 15]

- packages/files/pip.conf
- packages/pips.sls
- pillar.example
Allow to configure pip first.
Helps when you need to either use a proxy, or an alternate index.
> pip: allow to drop a config file first

- packages/defaults.yaml
Fix **rendering error** when no `packages.pips.config" pillar is unavailable.
> Add 'pips.config' dict to defaults

- CHANGELOG.rst
- README.rst
- kitchen.yml
- packages/defaults.yaml
- packages/gems.sls
- packages/init.sls
- packages/npms.sls
- packages/pips.sls
- packages/pkgs.sls
- packages/snaps.sls
- pillar.example
- test/integration/default/npms_spec.rb
> Add npm management support

- packages/archives.sls
- packages/defaults.yaml
- packages/gems.sls
- packages/npms.sls
- packages/pips.sls
- packages/pkgs.sls
- packages/snaps.sls
- pillar.example
This PR adds retry for internet dependent states.
For example workaround "Temporary failure in name resolution" issue.
```
ID: packages-archive-wanted-download-kubectl
Function: file.managed
Name: /usr/local/bin/kubectl
Result: False
Comment: Failed to cache 
https://storage.googleapis.com/kubernetes-release/release/v1.12.3/bin/linux/amd64/kubectl: 
Error: [Errno -3] Temporary failure in name resolution reading 
https://storage.googleapis.com/kubernetes-release/release/v1.12.3/bin/linux/amd64/kubectl
Started: 03:26:55.100108
Duration: 2635.434 ms
```
> feat(internet): add retries for internet dependent states

- kitchen.yml
- packages/osfamilymap.yaml
- pillar.example
- test/salt/pillar/debian.sls
- test/salt/pillar/ubuntu.sls
---
No.
The `epel` state is required by default, but it's not actually needed. 
Here is unnecessary failures - python2-pip is already installed so epel is not a hard requirement.
```
ID: pip_req_pkgs
Function: pkg.installed
Result: True
Comment: 2 targeted packages were installed/updated.
The following packages were already installed: gcc
Started: 10:53:20.147587
Duration: 19811.277 ms
Changes:
----------
python-backports:
----------
new:
1.0-8.el7
old:
python-backports-ssl_match_hostname:
----------
new:
3.5.0.1-1.el7
old:
python-devel:
----------
new:
2.7.5-86.el7
old:
python-ipaddress:
----------
new:
1.0.16-2.el7
old:
python-rpm-macros:
----------
new:
3-32.el7
old:
python-setuptools:
----------
new:
0.9.8-7.el7
old:
python2-pip:
----------
new:
8.1.2-10.el7
old:
python2-rpm-macros: …
```
> feat(centos): epel is not hard requirement for pip

- packages/osfamilymap.yaml
This PR updates osfamilymap.yaml for python3.
Move away from python2 per https://python3statement.org/
The problem is, when your OS only has python3, but formulas reference python2 packages, then python2 gets installed and potentially changes `python` symlink back to `python2`.
I cannot find a RedHat python3-devel package either.
> fix(python): os default to python3

- .github/workflows/kitchen.vagrant.yml
- .github/workflows/kitchen.windows.yml
- Gemfile
- Gemfile.lock
- docs/README.rst
- kitchen.vagrant.yml
- kitchen.windows.yml
- kitchen.yml
- pillar.example
- test/integration/default/controls/pkgs_spec.rb
- test/integration/windows/README.md
- test/integration/windows/controls/pkgs_spec.rb
- test/integration/windows/inspec.yml
- test/salt/pillar/windows.sls
---
No.
Built upon the work done by @dafyddj in other formulas:
* https://github.com/saltstack-formulas/openvpn-formula/pull/129
* https://github.com/saltstack-formulas/salt-formula/pull/471
Brings in automated testing for Chocolatey as discussed in #60 (CC: @kartnico).
Add Windows testing for Chocolatey installations.
As provided.
As seen in the GitHub Actions logs.
@dafyddj As mentioned in Slack, I haven't managed to get the Vagrant testing working yet so I'd appreciate it if you have any suggestions for that.
Using this PR as a precursor to providing Windows testing configuration via. the `ssf-formula`.
> ci(windows): test using GitHub Actions

- packages/archives.sls
- packages/chocolatey.sls
- packages/init.sls
- packages/map.jinja
- packages/npms.sls
- packages/pkgs.sls
- packages/remote_pkgs.sls
- packages/snaps.sls
My use case is that I actually have to rename this formula because the SUSE Manager ships with its own `packages` formula that it uses internally. But I still want to use this formula in combination. So one of them has to be renamed. This change makes that way easier.
---
No.
Use relative state include.
> refactor: Use relative state include

- pillar.example
- test/integration/default/controls/archives_spec.rb
- test/integration/default/files/_mapdata/debian-10.yaml
- test/integration/default/files/_mapdata/debian-11.yaml
- test/integration/default/files/_mapdata/debian-9.yaml
- test/integration/default/files/_mapdata/ubuntu-18.yaml
- test/integration/default/files/_mapdata/ubuntu-20.yaml
- test/salt/pillar/debian.sls
- test/salt/pillar/ubuntu.sls
---
No.
This PR is to fix failing CI.
> ci(example): remove blockbox as example of raw
